core:
  - changed-files:
      - any-glob-to-any-file: src/core/**

plugin:
  - changed-files:
      - any-glob-to-any-file: src/plugin/**

security:
  - changed-files:
      - any-glob-to-any-file: src/security/**

adapters:
  - changed-files:
      - any-glob-to-any-file:
          - src/plugin/schema.ts
          - src/plugin/store.ts
